apiVersion: apps/v1
kind: Deployment
metadata:
  name: prices-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prices
  template:
    metadata:
      labels:
        app: prices
    spec:
      containers:
        - name: prices
          image: predicrypt/prices
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: prices-srv
spec:
  selector:
    app: prices
  ports:
    - name: prices
      protocol: TCP
      port: 3000
      targetPort: 3000
