apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
    nginx.ingress.kubernetes.io/websocket-services: prices-srv
spec:
  rules:
    - host: predicrypt.com
      http:
        paths:
          - path: /auth/?(.*)
            backend:
              serviceName: auth-srv
              servicePort: 3000
          - path: /prices/?(.*)
            backend:
              serviceName: prices-srv
              servicePort: 3000
          - path: /orders/?(.*)
            backend:
              serviceName: orders-srv
              servicePort: 3000
          - path: /users/?(.*)
            backend:
              serviceName: users-srv
              servicePort: 3000    
          - path: /?(.*)
            backend:
              serviceName: front-srv
              servicePort: 4200    
