apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ../k8s/deployments/*
build:
  local:
    push: false
  artifacts:
    - image: predicrypt/auth
      context: ../../auth-service
      docker:
        dockerfile: Dockerfile
        buildArgs:
          GITHUB_TOKEN: "{{.GITHUB_TOKEN}}"
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    #- image: predicrypt/prices
     # context: ../../prices-service
      #docker:
       # dockerfile: Dockerfile
        #buildArgs:
         # GITHUB_TOKEN: "{{.GITHUB_TOKEN}}"
      #sync:
       # manual:
        #  - src: 'src/**/*.ts'
         #   dest: .
    - image: predicrypt/orders
      context: ../../orders-service
      docker:
        dockerfile: Dockerfile
        buildArgs:
          GITHUB_TOKEN: "{{.GITHUB_TOKEN}}"
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: predicrypt/users
      context: ../../users-service
      docker:
        dockerfile: Dockerfile
        buildArgs:
          GITHUB_TOKEN: "{{.GITHUB_TOKEN}}"
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .

    - image: predicrypt/front
      context: ../../front
      docker:
        dockerfile: Dockerfile
        buildArgs:
          GITHUB_TOKEN: "{{.GITHUB_TOKEN}}"
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
